name: build_images

on:
  push:
jobs:
  build_and_push_to_dockerHub:
    name: Build and push docker image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push powerapi-base-ci image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          file: Dockerfile-powerapi-base-ci
          tags: powerapi/powerapi-base-ci:latest
      - name: Build and push powerapi-build-deb image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          file: Dockerfile-powerapi-build-deb
          tags: powerapi/powerapi-build-deb:latest

